# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_content', models.CharField(max_length=255)),
                ('fqdn', models.CharField(max_length=255)),
                ('grains', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_content', models.CharField(max_length=255)),
                ('ipv4', models.CharField(max_length=15)),
                ('mask', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('minion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salt_observer.Minion')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salt_observer.Network')),
            ],
        ),
        migrations.AddField(
            model_name='minion',
            name='networks',
            field=models.ManyToManyField(through='salt_observer.NetworkInterface', to='salt_observer.Network'),
        ),
    ]
