# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 09:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt_observer', '0002_auto_20160317_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='minion',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
