# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salt_observer', '0002_auto_20160317_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='ipv4_subnet',
        ),
        migrations.RemoveField(
            model_name='network',
            name='ipv6_subnet',
        ),
    ]
