# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt_observer', '0003_minion_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
