# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt_observer', '0003_auto_20160317_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='ipv6',
        ),
        migrations.AddField(
            model_name='network',
            name='mask',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
