# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('salt_observer', '0004_networkinterface_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minion',
            old_name='timestamp',
            new_name='last_updated',
        ),
        migrations.AddField(
            model_name='network',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 15, 12, 39, 8, 682138, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
