# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt_observer', '0007_auto_20160712_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(max_length=255)),
                ('minion', models.ManyToManyField(to='salt_observer.Minion')),
            ],
        ),
    ]
