# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt_observer', '0008_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='minion',
            field=models.ManyToManyField(blank=True, to='salt_observer.Minion'),
        ),
    ]
