# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt_observer', '0009_auto_20160712_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='can_speak_https',
            field=models.BooleanField(default=False, help_text='Is there a service listening on port 443'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='public',
            field=models.BooleanField(default=False, help_text='Is this domain public accessible'),
            preserve_default=False,
        ),
    ]
