# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt_observer', '0010_auto_20160712_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='_ssl_lab_grades',
            field=models.TextField(default='{}'),
        ),
    ]
