# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salt_observer', '0011_domain__ssl_lab_grades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='_ssl_lab_grades',
            new_name='_ssl_lab_status',
        ),
    ]
