# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt_observer', '0012_auto_20160712_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='valid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
