# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt_observer', '0013_domain_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='md_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
