# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-19 13:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salt_observer', '0015_auto_20160718_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='md_last_autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domain',
            name='md_last_edited',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 19, 13, 39, 49, 713447, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minion',
            name='md_last_autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minion',
            name='md_last_edited',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 19, 13, 39, 55, 586008, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='md_last_autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='network',
            name='md_last_edited',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 19, 13, 40, 0, 498161, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
