# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt_observer', '0016_auto_20160719_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='ip_address',
            field=models.CharField(default='', max_length=17),
            preserve_default=False,
        ),
    ]
